# coding: utf-8

"""
    Golem unlimited low level hub API

    API description in Markdown.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gu_rest_api
from gu_rest_api.api.default_api import DefaultApi  # noqa: E501
from gu_rest_api.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = gu_rest_api.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_peers_node_id_deployments_get(self):
        """Test case for peers_node_id_deployments_get

        """
        pass

    def test_peers_node_id_deployments_post(self):
        """Test case for peers_node_id_deployments_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
