# coding: utf-8

"""
    Golem unlimited low level hub API

    API description in Markdown.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gu_rest_api
from gu_rest_api.api.session_api import SessionApi  # noqa: E501
from gu_rest_api.rest import ApiException


class TestSessionApi(unittest.TestCase):
    """SessionApi unit test stubs"""

    def setUp(self):
        self.api = gu_rest_api.api.session_api.SessionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_hub_session_peers(self):
        """Test case for add_hub_session_peers

        Manually adds peers to hub session  # noqa: E501
        """
        pass

    def test_create_blob(self):
        """Test case for create_blob

        Creates new lob  # noqa: E501
        """
        pass

    def test_create_hub_session(self):
        """Test case for create_hub_session

        Creates new hub session.  # noqa: E501
        """
        pass

    def test_create_peer_session(self):
        """Test case for create_peer_session

        Creates new deploymnet  # noqa: E501
        """
        pass

    def test_delete_hub_session(self):
        """Test case for delete_hub_session

        """
        pass

    def test_delete_peer_session(self):
        """Test case for delete_peer_session

        """
        pass

    def test_download_blob(self):
        """Test case for download_blob

        Downloads binary content from the hub  # noqa: E501
        """
        pass

    def test_get_hub_session(self):
        """Test case for get_hub_session

        Gets hub session info  # noqa: E501
        """
        pass

    def test_get_hub_session_config(self):
        """Test case for get_hub_session_config

        Gets configuration from stash  # noqa: E501
        """
        pass

    def test_list_hub_session_blobs(self):
        """Test case for list_hub_session_blobs

        Lists currently allocated lobs  # noqa: E501
        """
        pass

    def test_list_hub_sessions(self):
        """Test case for list_hub_sessions

        Lists current hub sessions.  # noqa: E501
        """
        pass

    def test_sessions_session_id_patch(self):
        """Test case for sessions_session_id_patch

        Hub session update  # noqa: E501
        """
        pass

    def test_set_hub_session_config(self):
        """Test case for set_hub_session_config

        Sets configuration stash  # noqa: E501
        """
        pass

    def test_update_peer_session(self):
        """Test case for update_peer_session

        Sends multiple commands for peer  # noqa: E501
        """
        pass

    def test_upload_blob(self):
        """Test case for upload_blob

        Uploads a binary content to the hub.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
