# coding: utf-8

"""
    Golem unlimited low level hub API

    API description in Markdown.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gu_rest_api
from gu_rest_api.api.peer_info_api import PeerInfoApi  # noqa: E501
from gu_rest_api.rest import ApiException


class TestPeerInfoApi(unittest.TestCase):
    """PeerInfoApi unit test stubs"""

    def setUp(self):
        self.api = gu_rest_api.api.peer_info_api.PeerInfoApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_peer_details(self):
        """Test case for get_peer_details

        Returns detailed peer info  # noqa: E501
        """
        pass

    def test_list_peers(self):
        """Test case for list_peers

        Returns a list hub peers.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
