# coding: utf-8

"""
    Golem unlimited low level hub API

    API description in Markdown.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gu_rest_api
from gu_rest_api.api.hub_session_api import HubSessionApi  # noqa: E501
from gu_rest_api.rest import ApiException


class TestHubSessionApi(unittest.TestCase):
    """HubSessionApi unit test stubs"""

    def setUp(self):
        self.api = gu_rest_api.api.hub_session_api.HubSessionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_hub_session_peers(self):
        """Test case for add_hub_session_peers

        Manually adds peers to hub session  # noqa: E501
        """
        pass

    def test_create_hub_session(self):
        """Test case for create_hub_session

        """
        pass

    def test_get_hub_session(self):
        """Test case for get_hub_session

        Gets hub session info  # noqa: E501
        """
        pass

    def test_get_hub_session_config(self):
        """Test case for get_hub_session_config

        Gets configuration from stash  # noqa: E501
        """
        pass

    def test_list_hub_sessions(self):
        """Test case for list_hub_sessions

        Lists current hub sessions.  # noqa: E501
        """
        pass

    def test_sessions_session_id_delete(self):
        """Test case for sessions_session_id_delete

        """
        pass

    def test_sessions_session_id_patch(self):
        """Test case for sessions_session_id_patch

        Hub session update  # noqa: E501
        """
        pass

    def test_set_hub_session_configuration(self):
        """Test case for set_hub_session_configuration

        Sets configuration stash  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
