# coding: utf-8

"""
    Golem unlimited low level hub API

    API description in Markdown.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import gu_rest_api
from gu_rest_api.api.lob_man_api import LobManApi  # noqa: E501
from gu_rest_api.rest import ApiException


class TestLobManApi(unittest.TestCase):
    """LobManApi unit test stubs"""

    def setUp(self):
        self.api = gu_rest_api.api.lob_man_api.LobManApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_blob(self):
        """Test case for create_blob

        Creates new lob  # noqa: E501
        """
        pass

    def test_download_blob(self):
        """Test case for download_blob

        """
        pass

    def test_list_hub_session_blobs(self):
        """Test case for list_hub_session_blobs

        Lists currently allocated lobs  # noqa: E501
        """
        pass

    def test_upload_blob(self):
        """Test case for upload_blob

        """
        pass


if __name__ == '__main__':
    unittest.main()
