# coding: utf-8

"""
    Golem unlimited low level hub API

    API description in Markdown.  # noqa: E501

    OpenAPI spec version: 1.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from gu_rest_api.api_client import ApiClient


class PeerSessionApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def create_peer_session(self, session_id, node_id, peer_session_spec, **kwargs):  # noqa: E501
        """create_peer_session  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_peer_session(session_id, node_id, peer_session_spec, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str session_id: (required)
        :param str node_id: GU Network node identifier (required)
        :param PeerSessionSpec peer_session_spec: (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.create_peer_session_with_http_info(session_id, node_id, peer_session_spec, **kwargs)  # noqa: E501
        else:
            (data) = self.create_peer_session_with_http_info(session_id, node_id, peer_session_spec, **kwargs)  # noqa: E501
            return data

    def create_peer_session_with_http_info(self, session_id, node_id, peer_session_spec, **kwargs):  # noqa: E501
        """create_peer_session  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_peer_session_with_http_info(session_id, node_id, peer_session_spec, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str session_id: (required)
        :param str node_id: GU Network node identifier (required)
        :param PeerSessionSpec peer_session_spec: (required)
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['session_id', 'node_id', 'peer_session_spec']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_peer_session" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'session_id' is set
        if ('session_id' not in local_var_params or
                local_var_params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `create_peer_session`")  # noqa: E501
        # verify the required parameter 'node_id' is set
        if ('node_id' not in local_var_params or
                local_var_params['node_id'] is None):
            raise ValueError("Missing the required parameter `node_id` when calling `create_peer_session`")  # noqa: E501
        # verify the required parameter 'peer_session_spec' is set
        if ('peer_session_spec' not in local_var_params or
                local_var_params['peer_session_spec'] is None):
            raise ValueError("Missing the required parameter `peer_session_spec` when calling `create_peer_session`")  # noqa: E501

        if 'node_id' in local_var_params and not re.search(r'0x[0-9a-f]{40}', local_var_params['node_id']):  # noqa: E501
            raise ValueError("Invalid value for parameter `node_id` when calling `create_peer_session`, must conform to the pattern `/0x[0-9a-f]{40}/`")  # noqa: E501
        collection_formats = {}

        path_params = {}
        if 'session_id' in local_var_params:
            path_params['sessionId'] = local_var_params['session_id']  # noqa: E501
        if 'node_id' in local_var_params:
            path_params['nodeId'] = local_var_params['node_id']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'peer_session_spec' in local_var_params:
            body_params = local_var_params['peer_session_spec']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['*/*'])  # noqa: E501

        # Authentication setting
        auth_settings = ['serviceToken', 'systemName']  # noqa: E501

        return self.api_client.call_api(
            '/sessions/{sessionId}/peer/{nodeId}/peer-sessions', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_peer_session(self, session_id, node_id, hub_session, **kwargs):  # noqa: E501
        """delete_peer_session  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_peer_session(session_id, node_id, hub_session, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str session_id: (required)
        :param str node_id: GU Network node identifier (required)
        :param str hub_session: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.delete_peer_session_with_http_info(session_id, node_id, hub_session, **kwargs)  # noqa: E501
        else:
            (data) = self.delete_peer_session_with_http_info(session_id, node_id, hub_session, **kwargs)  # noqa: E501
            return data

    def delete_peer_session_with_http_info(self, session_id, node_id, hub_session, **kwargs):  # noqa: E501
        """delete_peer_session  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_peer_session_with_http_info(session_id, node_id, hub_session, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str session_id: (required)
        :param str node_id: GU Network node identifier (required)
        :param str hub_session: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['session_id', 'node_id', 'hub_session']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_peer_session" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'session_id' is set
        if ('session_id' not in local_var_params or
                local_var_params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `delete_peer_session`")  # noqa: E501
        # verify the required parameter 'node_id' is set
        if ('node_id' not in local_var_params or
                local_var_params['node_id'] is None):
            raise ValueError("Missing the required parameter `node_id` when calling `delete_peer_session`")  # noqa: E501
        # verify the required parameter 'hub_session' is set
        if ('hub_session' not in local_var_params or
                local_var_params['hub_session'] is None):
            raise ValueError("Missing the required parameter `hub_session` when calling `delete_peer_session`")  # noqa: E501

        if 'node_id' in local_var_params and not re.search(r'0x[0-9a-f]{40}', local_var_params['node_id']):  # noqa: E501
            raise ValueError("Invalid value for parameter `node_id` when calling `delete_peer_session`, must conform to the pattern `/0x[0-9a-f]{40}/`")  # noqa: E501
        collection_formats = {}

        path_params = {}
        if 'session_id' in local_var_params:
            path_params['sessionId'] = local_var_params['session_id']  # noqa: E501
        if 'node_id' in local_var_params:
            path_params['nodeId'] = local_var_params['node_id']  # noqa: E501
        if 'hub_session' in local_var_params:
            path_params['hubSession'] = local_var_params['hub_session']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['serviceToken', 'systemName']  # noqa: E501

        return self.api_client.call_api(
            '/sessions/{sessionId}/peer/{nodeId}/peer-sessions/{hubSession}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def update_peer_session(self, session_id, node_id, hub_session, command, **kwargs):  # noqa: E501
        """Sends multiple commands for peer  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_peer_session(session_id, node_id, hub_session, command, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str session_id: (required)
        :param str node_id: GU Network node identifier (required)
        :param str hub_session: (required)
        :param list[Command] command: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.update_peer_session_with_http_info(session_id, node_id, hub_session, command, **kwargs)  # noqa: E501
        else:
            (data) = self.update_peer_session_with_http_info(session_id, node_id, hub_session, command, **kwargs)  # noqa: E501
            return data

    def update_peer_session_with_http_info(self, session_id, node_id, hub_session, command, **kwargs):  # noqa: E501
        """Sends multiple commands for peer  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.update_peer_session_with_http_info(session_id, node_id, hub_session, command, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str session_id: (required)
        :param str node_id: GU Network node identifier (required)
        :param str hub_session: (required)
        :param list[Command] command: (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['session_id', 'node_id', 'hub_session', 'command']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method update_peer_session" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'session_id' is set
        if ('session_id' not in local_var_params or
                local_var_params['session_id'] is None):
            raise ValueError("Missing the required parameter `session_id` when calling `update_peer_session`")  # noqa: E501
        # verify the required parameter 'node_id' is set
        if ('node_id' not in local_var_params or
                local_var_params['node_id'] is None):
            raise ValueError("Missing the required parameter `node_id` when calling `update_peer_session`")  # noqa: E501
        # verify the required parameter 'hub_session' is set
        if ('hub_session' not in local_var_params or
                local_var_params['hub_session'] is None):
            raise ValueError("Missing the required parameter `hub_session` when calling `update_peer_session`")  # noqa: E501
        # verify the required parameter 'command' is set
        if ('command' not in local_var_params or
                local_var_params['command'] is None):
            raise ValueError("Missing the required parameter `command` when calling `update_peer_session`")  # noqa: E501

        if 'node_id' in local_var_params and not re.search(r'0x[0-9a-f]{40}', local_var_params['node_id']):  # noqa: E501
            raise ValueError("Invalid value for parameter `node_id` when calling `update_peer_session`, must conform to the pattern `/0x[0-9a-f]{40}/`")  # noqa: E501
        collection_formats = {}

        path_params = {}
        if 'session_id' in local_var_params:
            path_params['sessionId'] = local_var_params['session_id']  # noqa: E501
        if 'node_id' in local_var_params:
            path_params['nodeId'] = local_var_params['node_id']  # noqa: E501
        if 'hub_session' in local_var_params:
            path_params['hubSession'] = local_var_params['hub_session']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'command' in local_var_params:
            body_params = local_var_params['command']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['serviceToken', 'systemName']  # noqa: E501

        return self.api_client.call_api(
            '/sessions/{sessionId}/peer/{nodeId}/peer-sessions/{hubSession}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
